name: e2e testing

on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Run E2E test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: yarn install
      - name: Create .env.test
        run: |
          cp .env.example .env.test
        shell: bash
      - name: docker-compose up for db:test
        run: yarn run db:test:restart
      - name: run e2e testing
        run: yarn run test:e2e 
  check-coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: test-report/*.xml    
          reporter: jest-junit